architdate/PKHeX-Plugins

- AutoLegalityMod/AutoModPlugins.csproj
- AutoLegalityMod/GUI/LiveHexUI.Designer.cs
- AutoLegalityMod/GUI/LiveHexUI.cs
- AutoLegalityMod/Properties/AutoLegality.Designer.cs
- AutoLegalityMod/Properties/AutoLegality.settings
- AutoLegalityMod/app.config
- AutoLegalityMod/packages.config
- PKHeX.Core.AutoMod/BotController/ICommunicator.cs
- PKHeX.Core.AutoMod/BotController/LiveHexController.cs
- PKHeX.Core.AutoMod/BotController/PokeSysBotMini.cs
- PKHeX.Core.AutoMod/BotController/RamOffsets.cs
- PKHeX.Core.AutoMod/BotController/SwitchCommand.cs
- PKHeX.Core.AutoMod/BotController/UsbBotMini.cs
- PKHeX.Core.AutoMod/PKHeX.Core.AutoMod.csproj
Perhaps a lot more has changed than required (the setting could just be pulled in RamOffsets.cs, I can revert to this if preferred and not pass the InjectorCommunicationType enum as it is right now)
Usage for other people that might be reading this:
USB-Botbase setup:
1) Install [USB-Botbase](https://github.com/fishguy6564/USB-Botbase) to console. Won't work at the same time as sys-botbase or other USB sysmodules or hb apps such as nxmtp.
2) Use [Zadig](http://www.unitrunker.com/zadig.html) to install libusbK while USB-Botbase is running and connected to device
3) Install [libusb](http://www.mediafire.com/file/wdx5lu4c37sm1cv/libusb-win32-devel-filter-1.2.6.0.exe/file) and create a filter for the switch
3a) And/or install [libusbdotnet](https://sourceforge.net/projects/libusbdotnet/) and …
> Add support for USB-Botbase

- setup_bleedingedge.ps1
- setup_stable.ps1
this fixes `Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel`, powershell defaults to tls v1.0 but some websites do not support this tls version anymore, [related stackoverflow question](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)
> set default tls request version of setup script

- PKHeX.Core.AutoMod/AutoMod/ShowdownEdits.cs
Fixes the second noted issue for #55 and completely closes #48 
Code is copied from kwsch/PKHeX@0111c3d making it somewhat redundant, but it does fix the issue.
> Showdown/Smogon imports now properly set Stat XP

- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
Simulates trading to a Generation 2 game. Catch Rate becomes updated to the corresponding valid Generation 2 item (requires kwsch/PKHeX@cc5a950)
Test case: RBY Mr. Mime with Fire Punch fails to legalize in the current version, but is successfully legalized with this PR
[122 - MARCEL - 77D7.zip](https://github.com/architdate/PKHeX-Plugins/files/5294352/122.-.MARCEL.-.77D7.zip)
> Legalizer now works with Generation 1 tradebacks

- PKHeX.Core.Enhancements/Teams/SmogonSetList.cs
Any Smogon Set that has Hidden Power now correctly recieves the type object
> Smogon set importer now respects Hidden Power types

- AutoLegalityMod/GUI/ShowdownSetLoader.cs
- AutoLegalityMod/Plugins/SmogonGenner.cs
- AutoLegalityMod/Properties/AutoLegality.Designer.cs
- AutoLegalityMod/Properties/AutoLegality.settings
- AutoLegalityMod/app.config
- PKHeX.Core.Enhancements/Teams/SmogonSetList.cs
Old behavior:
Gather all sets for a given pokemon, import them all immediately via the showdown import function
If there is only one set, the importer asks to confirm before adding it to the tabs
If there is more than one set, the importer imports to boxes without user input
New proposed behavior:
Gather all sets for a given pokemon, prompt user for importing for each (include format and name for these sets)
If only one set is imported, the importer moves it to the tabs immediately without asking again
If more than one set are imported, they are imported to boxes without further input
If no sets are imported, don't import anything
Not sure if this behavior is better or not so I'm flagging this one as a draft
> Add optional prompts for smogon imports

- AutoLegalityMod/Plugins/SettingsEditor.cs
Very minor edit. 
Settings are already saved here: https://github.com/architdate/PKHeX-Plugins/blob/6350eea41d4f2f3690865f3f6ee18100dcd8cd07/AutoLegalityMod/GUI/ALMSettings.cs#L23-L29
Saving twice is redundant. Tested and confirmed that settings changes still persist between sessions.
> Remove unnecessary duplicate save for settings

- PKHeX.Core.Enhancements/Teams/SmogonSetList.cs
Adds support for the newly-added PKHeX Stadium 2 format SK2
> Add Stadium 2 support to Smogon Gen

- PKHeX.Core.AutoMod/Enhancements/ModLogic.cs
For pokemon that do not have valid encounters in Generation 2, generates Generation 1 encounters to complete the dex.
> Add support for pokemon unobtainable in Gen 2 for Living Dex

- AutoLegalityMod/GUI/ShowdownSetLoader.cs
- AutoLegalityMod/Properties/AutoLegality.Designer.cs
- AutoLegalityMod/Properties/AutoLegality.settings
- AutoLegalityMod/app.config
- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
Adds an option that, when enabled, will set a past-gen PK8's Battle Version assuming the Pokemon's moveset would still be legal. If the Pokemon's learnset would not be legal with a Battle Version set, this option does nothing.
With the option enabled: https://gfycat.com/SelfreliantFearfulIndianhare
With the option disabled: https://gfycat.com/WaryPleasingClownanemonefish
Currently on by default, though this can be changed.
> Add option for Legalizer to set Battle Version for Pokemon who meet the criteria

- PKHeX.Core.Enhancements/Teams/SmogonSetList.cs
Now properly imports pokemon with the "-GMax" identifier on their showdown export as Gigantamax pokemon. Replaces/invalidates the implementation of #75
> Properly import Gmax via smogon importer

- setup_bleedingedge.ps1
- setup_stable.ps1
`-UseBasicParsing` should be used to support user which are on a windows version which doesn't have Internet Explorer engine  installed and it was missing on some requests 👍
> add missing -UseBasicParsing to setup scripts

- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
Fix for hyper training special attack when specified 0-3
Allows for niche sets that utilize attacking a friendly pokemon ie. Surf Dragapult on a friendly Coalossal for WP proc
Uses same logic as Atk & Spe
> Niche Competitive Fix

- AutoLegalityMod/GUI/LiveHexUI.cs
- PKHeX.Core.Injection/BotController/Controllers/UsbBotMini.cs
LiveHex currently connects to the first USB device it finds, which is rarely desirable in an environment where multiple Switches are connected via USB.
These small changes allow a user to specify a USB port they'd like to connect to by leaving the "Port" box visible and filtering out USB ports that don't match the input. USB port can be obtained as outlined in USB-Botbase's setup guide in SysBot's wiki.
> Allow USB port specification in order to connect to a specific USB device.

- PKHeX.Core.Injection/LiveHeXBlockClasses/SwayGrass.cs
ChainEncounterSpecies and ChainEncounterLevel indicates the species and level of the Pokémon encountered if chain is active.
> Rename ChainSpeciesId and ChainLevel for clarity

- PKHeX.Core.Enhancements/Teams/SmogonSetList.cs
Simple fix to match similar implementations for Farfetch'd and Meowstic. Fixes URL error when genning sets for Sirfetch'd.
> [Smogon Import] Add proper handling for Sirfetch'd and Indeedee

- setup_bleedingedge.ps1
File cleanup is not complete for bleeding edge. `-Force` overwrites any files that don't get deleted, which is cleaner than just constantly expanding the files to remove.
> Use -Force on Expand-Archive

- AutoLegalityMod/GUI/LiveHexUI.cs
This fix allows the editor for the custom SwayGrass block to be opened in LiveHeX.
> Fix LiveHeX custom block editor

- AutoLegalityMod/GUI/ALMError.Designer.cs
- AutoLegalityMod/GUI/ALMError.cs
- AutoLegalityMod/GUI/ShowdownSetLoader.cs
- AutoLegalityMod/Plugins/AutoModPlugin.cs
- AutoLegalityMod/Plugins/LegalizeBoxes.cs
- Directory.Build.props
- PKHeX.Core.AutoMod/AutoMod/Trainers/TrainerSettings.cs
- PKHeX.Core.AutoMod/AutoMod/Util/Version.cs
Bring ALM error to front.
Change versioning code.
Fix `trainers` folder.
> Add build timestamp and build version to `Directory.Build.props`.

- AutoModTests/ShowdownSets/Anubis Tests/Anubis - pk9.txt
- AutoModTests/ShowdownSets/RoCs-PC Tests/RoC - pk9.txt
- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
- PKHeX.Core.AutoMod/AutoMod/Legalization/ShowdownEdits.cs
- PKHeX.Core.AutoMod/AutoMod/Legalization/SimpleEdits.cs
Fix Walking Wake, Iron Leaves, MightiestMark and Fly Pikachu, fix Tauros-Paldea test sets, add more sets.
> Fix setting HW scalar when not intended

- AutoLegalityMod/GUI/ALMSettings.cs
- AutoLegalityMod/GUI/ShowdownSetLoader.cs
- AutoLegalityMod/Plugins/LivingDex.cs
- AutoLegalityMod/Properties/AutoLegality.Designer.cs
- AutoLegalityMod/Properties/AutoLegality.settings
- AutoLegalityMod/app.config
- AutoModTests/LivingDexTests.cs
- AutoModTests/TeamTests.cs
- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
- PKHeX.Core.AutoMod/AutoMod/Legalization/Legalizer.cs
- PKHeX.Core.AutoMod/AutoMod/Legalization/SimpleEdits.cs
- PKHeX.Core.AutoMod/AutoMod/Regeneration/RegenTemplate.cs
- PKHeX.Core.AutoMod/AutoMod/Regeneration/RegenTemplateExtensions.cs
- PKHeX.Core.AutoMod/Enhancements/ModLogic.cs
- Hopefully fix living dex (Vivillon family, Gholdengo, handle some missing forms).
- Add an option to generate a native living dex (no transfers, only what's available in game version pairs).
- Pass correct generation context to `RegenTemplate`.
> Living dex fixes

- AutoLegalityMod/GUI/ALMSettings.Designer.cs
- AutoLegalityMod/GUI/ALMSettings.cs
- AutoLegalityMod/GUI/ShowdownSetLoader.cs
- AutoLegalityMod/GUI/WinFormsUtil.cs
- AutoLegalityMod/Plugins/AutoModPlugin.cs
- AutoLegalityMod/Plugins/LegalizeBoxes.cs
- AutoLegalityMod/Properties/AutoLegality.Designer.cs
- AutoLegalityMod/app.config
- AutoModTests/FeatureTests.cs
- AutoModTests/ShowdownSets/Anubis Tests/Anubis - pk9.txt
- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
- PKHeX.Core.AutoMod/AutoMod/Util/Version.cs
- Add option to temporarily disable version mismatch warnings.
- Check latest Core version and resume nagging if a user has been skipping updates for too long.
- Add test set for Vivillon, add test for version mismatch.
> Update check tweaks.

- README.md
Noticed the url to the appveyor.yml file was broken, hence the PR.
> Replace appveyor with Azure Pipelines in Readme

- AutoModTests/ShowdownSets/Anubis Tests/Anubis - pa8.txt
- AutoModTests/ShowdownSets/Anubis Tests/Anubis - pk8.txt
- AutoModTests/ShowdownSets/Anubis Tests/Anubis - pk9.txt
Adds some tests for HOME 3.0.  Should all be based on legal files. 
I'm unsure if the Eevee in LA needs to have its size values set a different way; it's from HOME 2.0 and has 0 HWS, hence is eligible for Mini Mark.
Worth noting that `Ball: Origin Ball` doesn't work in LA.
> Add Showdown Set tests for Home 3.0

- AutoModTests/ShowdownSets/Anubis Tests/Anubis - pk9.txt
Gets the LA overworld mons with crossover locations to pass.
Origin Ball issue is because of needing the enum, rather than the name.
> Tweak some crossover test sets, fix LAOrigin test set

- AutoLegalityMod/Plugins/GPSSPlugin.cs
- PKHeX.Core.Enhancements/Enhancements/NetUtil.cs
As of 2023-06-17 @ 6:21 PM (AST) all FlagBrew V1 endpoints were disabled, this means that uploading to GPSS in the current version of PKHeX-Plugins is no longer possible.
This PR aims to fix that and to also rewrite the uploading function to be a bit more modern.
- Fixed uploading to GPSS by switching to v2 endpoint
- Cleaned up upload code and added a bit more context to error messages that get returned.
- There is still a TODO that can only be done by me on the actual service side, but for now this should be acceptable.
> Fix GPSS Uploading

- PKHeX.Core.AutoMod/AutoMod/APILegality.cs
- Only grab encounters from the current version pair if AllowHomeTransferGeneration is set to false
- Modify the legality check settings to block All transfer encounters and not just GO, Home Gifts and prior to gen 8 mons. e.g. SV pikachu with Galar Champion Ribbon.
> Modify HOME Tracker checks

- PKHeX.Core.AutoMod/Enhancements/ModLogic.cs
Fixes expected count failing to find valid encounters for Scatterbug and Spewpa
Fixes VerifyDex unit test
> Fix Living Dex generation in Gen 9
